# Use a base image
FROM debian:bullseye-slim

# Add user 'necesse', don't run stuff as root!!
ARG user=container
ARG group=container
ARG uid=1000
ARG gid=1000


RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/bash -m ${user} --home /home/${user}

RUN dpkg --add-architecture i386
RUN apt update; apt install -y ca-certificates-java ca-certificates openssl git tar bash sqlite fontconfig
RUN apt update; apt install -y lib32gcc-s1 curl openjdk-17-jre-headless

# Download and extract SteamCMD
RUN mkdir -p /steamapps
RUN curl -sqL https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar zxvf - -C /steamapps
WORKDIR /steamapps

# Create the update_necesse.txt file
RUN echo '@ShutdownOnFailedCommand 1' >> update_necesse.txt \
    && echo '@NoPromptForPassword 1' >> update_necesse.txt \
    && echo 'force_install_dir /app/' >> update_necesse.txt \
    && echo 'login anonymous' >> update_necesse.txt \
    && echo 'app_update 1169370 validate' >> update_necesse.txt \
    && echo 'quit' >> update_necesse.txt

RUN echo $(date) && ./steamcmd.sh +runscript update_necesse.txt

RUN         cd /tmp/ \
            && curl -sSL https://github.com/gorcon/rcon-cli/releases/download/v0.10.3/rcon-0.10.3-amd64_linux.tar.gz > rcon.tar.gz \
            && tar xvf rcon.tar.gz \
            && mv rcon-0.10.3-amd64_linux/rcon /usr/local/bin/

# Saves will be available under /root/.config/Necesse/saves
RUN mkdir -p /home/container/.config/Necesse
RUN chown -R 1000:1000 /home/container
RUN chown -R 1000:1000 /root


USER ${user}
ENV  USER=${user} HOME=/home/${user}

# Set the working directory and create entrypoint.sh
WORKDIR /home/container
RUN tee entrypoint.sh <<'EOF'
    #!/bin/sh
    MODIFIED_STARTUP=`eval echo $(echo ${STARTUP} | sed -e 's/{{/${/g' -e 's/}}/}/g')`
    echo ":/home/container$ ${MODIFIED_STARTUP}"

    ${MODIFIED_STARTUP}
EOF
    
RUN chmod +x entrypoint.sh


# Set the entry point for the container
CMD ["./entrypoint.sh"]
